export const FETCH_PASSENGER_REQUEST = "FETCH_PASSENGER_REQUEST";
export const FETCH_PASSENGER_SUCCESS = "FETCH_PASSENGER_SUCCESS";
export const FETCH_PASSENGER_FAILURE = "FETCH_PASSENGER_FAILURE";
export const FETCH_PASSENGER_BYID_REQUEST = "FETCH_PASSENGER_BYID_REQUEST";
export const FETCH_PASSENGER_BYID_SUCCESS = "FETCH_PASSENGER_BYID_SUCCESS";
export const FETCH_PASSENGER_BYID_FAILURE = "FETCH_PASSENGER_BYID_FAILURE";
