export const FETCH_PASSENGER_REQUEST = "FETCH_PASSENGER_REQUEST";
export const FETCH_PASSENGER_SUCCESS = "FETCH_PASSENGER_SUCCESS";
export const FETCH_PASSENGER_FAILURE = "FETCH_PASSENGER_FAILURE";
export const SET_PASSENGER = "SET_PASSENGER";
export const SET_PASSENGER_ID = "SET_PASSENGER_ID";
export const SET_SCREEN = "SET_SCREEN";
